FROM node:20-alpine
ARG DATABASE_URL

WORKDIR /usr/src/app

COPY . .
RUN yarn install
RUN cd packages/db && DATABASE_URL=$DATABASE_URL npx prisma generate && cd ../..
ENV DATABASE_URL=$DATABASE_URL
RUN yarn build

EXPOSE 3000

CMD ["npm", "run", "start"]

