FROM node:20-alpine

RUN apk update && apk add --no-cache openssl

WORKDIR /usr/src/app

COPY . .

RUN npm install --legacy-peer-deps
RUN npx prisma generate --schema packages/db/prisma/schema.prisma
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
