FROM node:20-alpine
ARG DATABASE_URL

WORKDIR /usr/src/app

COPY . .

RUN npm install
RUN cd packages/db && DATABASE_URL=$DATABASE_URL npx prisma generate && cd ../..
## put DATABASE_URL in apps/web/.env
RUN echo DATABASE_URL=$DATABASE_URL >> apps/web/.env
RUN DATABASE_URL=$DATABASE_URL npm run build
## Remove .env file
RUN rm apps/web/.env

EXPOSE 3000

CMD ["npm", "run", "start"]